security:
  enableLogin: false
  csrfDisabled: false
  loginAttemptCount: 5
  loginResetTimeMinutes: 60
  initialLogin:
    username: korb-admin
    password: KorbPDF!2024
  oauth2:
    enabled: false

system:
  defaultLocale: en_GB
  googlevisibility: false
  enableAlphaFunctionality: false
  showUpdate: false
  showUpdateOnlyAdmin: false
  customHTMLFiles: true
  tessdataDir: /usr/share/tessdata
  enableAnalytics: false

ui:
  appName: Korb Engineering PDF Tools
  homeDescription: Internal PDF processing suite — Korb Engineering
  appNameNavbar: KE PDF TOOLS

endpoints:
  toRemove: []
  groupsToRemove: []

premium:
  enabled: false
  key: ""
